[package]
name = "sqlite-http"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite-loadable = "0.0.6-alpha.6"
reqwest = { version = "0.11", features = ["blocking"] }
sqlite-reader = { git = "https://github.com/asg017/sqlite-reader.git" }


[lib]
crate-type=["lib", "staticlib", "cdylib"]
